"""
One‑click runner: executes all experiments and then aggregates results into a CSV file.

This script searches for YAML configuration files generated by create_config_files.py.
The directory structure is:
    ./config/{group_type}/{ordering_type}/orbit_num{orbit_num}_group_order{group_order}/{method}_config.yaml

The script processes them sequentially using the `process` function from `src.main`.

Results are saved as follows:
    - Individual experiment results (info CSV, transport matrix PNG, etc.) are stored under
      ./result/{group_type}/{ordering_type}/orbit_num{orbit_num}_group_order{group_order}/
    - Aggregated all records (each row corresponds to one experiment) are written to:
      ./result/all_records.csv
"""

import yaml
import glob
import os
import re
import pandas as pd
from src.main import process


def run_all_configs():
    print("Searching for configuration files...\n")

    ROT_files = []
    ROT_files.extend(glob.glob("./config/*/*/*/LOT_config.yaml", recursive=True))
    ROT_files.extend(glob.glob("./config/*/*/*/EROT_config.yaml", recursive=True))
    print(f"Found {len(ROT_files)} ROT config file(s)")

    C_ROT_files = []
    C_ROT_files.extend(glob.glob("./config/*/*/*/C_LOT_config.yaml", recursive=True))
    C_ROT_files.extend(glob.glob("./config/*/*/*/C_EROT_config.yaml", recursive=True))
    print(f"Found {len(C_ROT_files)} C_ROT config file(s)")

    SG_ROT_files = []
    SG_ROT_files.extend(glob.glob("./config/*/*/*/SG_LOT_config.yaml", recursive=True))
    SG_ROT_files.extend(glob.glob("./config/*/*/*/SG_EROT_config.yaml", recursive=True))
    print(f"Found {len(SG_ROT_files)} SG_ROT config file(s)")

    total_files = len(ROT_files) + len(C_ROT_files) + len(SG_ROT_files)
    print(f"Total config files found: {total_files}\n")

    print("Starting batch processing...")
    success_count = 0

    for files, name in [(ROT_files, "ROT"), (C_ROT_files, "C_ROT"), (SG_ROT_files, "SG_ROT")]:
        if files:
            print(f"\nProcessing {name} files...")
            files.sort()
            for i, config_path in enumerate(files, 1):
                print(f"\n[{i}/{len(files)}] Processing: {config_path}")
                try:
                    with open(config_path, "r", encoding="utf-8") as f:
                        config = yaml.safe_load(f)
                    process(config)
                    success_count += 1
                    print("✓ Processing succeeded")
                except Exception as e:
                    print(f"✗ Processing failed: {e}")

    print("\n" + "=" * 60)
    print(f"Processing completed! Successfully processed: {success_count}/{total_files}\n")


def aggregate_results():
    print("Aggregating results...\n")
    records = []
    pattern = os.path.join("./result", "*", "*", "orbit_num*_group_order*", "*_info.csv")

    for csv_path in glob.glob(pattern, recursive=True):
        parts = csv_path.split(os.sep)
        group_type = parts[-4]
        ordering_type = parts[-3]
        num_order = parts[-2]
        filename = parts[-1]
        method = filename.replace('_info.csv', '')

        match = re.match(r"orbit_num(\d+)_group_order(\d+)", num_order)
        if match:
            orbit_num = int(match.group(1))
            group_order = int(match.group(2))
        else:
            continue

        df = pd.read_csv(csv_path)
        for _, row in df.iterrows():
            records.append({
                "group_type": group_type,
                "ordering_type": ordering_type,
                "orbit_num": orbit_num,
                "group_order": group_order,
                "method": method,
                "time": row.get("time", None),
                "cost": row.get("cost", None),
                "matrix_distance": row.get("matrix_distance", None),
            })

    if not records:
        print("No records found. Skipping aggregation.")
        return

    df = pd.DataFrame(records)

    method_order = {'LOT': 1, 'C_LOT': 2, 'SG_LOT': 3,
                    'EROT': 4, 'C_EROT': 5, 'SG_EROT': 6}
    df['method_rank'] = df['method'].map(method_order)
    df_sorted = df.sort_values(
        by=['group_type', 'ordering_type', 'orbit_num', 'group_order', 'method_rank']
    ).drop(columns=['method_rank'])

    save_path = "./result/all_records.csv"
    df_sorted.to_csv(save_path, index=False, encoding="utf-8-sig", float_format='%.6f')
    print(f"CSV saved: {save_path}\n")

if __name__ == "__main__":
    run_all_configs()
    aggregate_results()